name: passman
description: "Passman — password manager lokal yang aman."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  cryptography: ^2.9.0
  path_provider: ^2.1.5
  otp: ^3.2.0
  file_selector: ^1.1.0
  window_manager: ^0.5.1
  tray_manager: ^0.3.2
  launch_at_startup: ^0.5.0
  package_info_plus: ^8.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.7

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.ico
    - assets/tray_icon.png

# Konfigurasi installer MSIX (dipakai oleh: dart run msix:create)
msix_config:
  display_name: Passman
  publisher_display_name: gxkuat brow
  identity_name: com.gxkuat.passman
  msix_version: 1.0.0.0
  logo_path: assets\tray_icon.png
  capabilities: runFullTrust
